
mod TOURLA is 

protecting TOUR .

sort ConfLA .
sort LastOpKey .
sort Key .


op k : -> EmptyTour .
op kit : Tour -> Tour .
op [_#_] : Conf LastOpKey -> ConfLA .


--- one trn should be compiled to 3 step trn
--- <Conf># => Conf#NeedKey => Conf#Key => Conf'#
--- ...#NeedKey => eq #NeedKey = Key
 
var TS : Tour .

eq kit ( w ( TS ) ) = w ( k ) .
eq kit ( b ( TS ) ) = b ( k ) .
eq kit ( 0 ) = 0 . 

endm

